---@alias BTD_RMG_OBJECT_TYPES
BTD_STATUE_OF_REVELATION = 1
BTD_SUN_RIDER_MONUMENT = 2
BTD_WARMEN_HOUSE = 3
BTD_KNOWLEDGE_MEGALITH = 4
BTD_DWARVEN_MINE = 5

while not BTD_NewObjects do 
    sleep()
end