---@alias ArtifactID
---|`ARTIFACT_SWORD_OF_RUINS`
---|`ARTIFACT_GREAT_AXE_OF_GIANT_SLAYING`
---|`ARTIFACT_WAND_OF_X`
---|`ARTIFACT_UNICORN_HORN_BOW`
---|`ARTIFACT_TITANS_TRIDENT`
---|`ARTIFACT_STAFF_OF_VEXINGS`
---|`ARTIFACT_SHACKLES_OF_WAR`
---|`ARTIFACT_FOUR_LEAF_CLOVER`
---|`ARTIFACT_ICEBERG_SHIELD`
---|`ARTIFACT_GOLDEN_SEXTANT`
---|`ARTIFACT_CROWN_OF_COURAGE`
---|`ARTIFACT_CROWN_OF_MANY_EYES`
---|`ARTIFACT_PLATE_MAIL_OF_STABILITY`
---|`ARTIFACT_BREASTPLATE_OF_PETRIFIED_WOOD`
---|`ARTIFACT_PEDANT_OF_MASTERY`
---|`ARTIFACT_NECKLACE_OF_BRAVERY`
---|`ARTIFACT_WEREWOLF_CLAW_NECKLACE`
---|`ARTIFACT_EVERCOLD_ICICLE`
---|`ARTIFACT_NECKLACE_OF_POWER`
---|`ARTIFACT_RING_OF_LIGHTING_PROTECTION`
---|`ARTIFACT_RING_OF_LIFE`
---|`ARTIFACT_RING_OF_HASTE`
---|`ARTIFACT_NIGHTMARISH_RING`
---|`ARTIFACT_BOOTS_OF_SPEED`
---|`ARTIFACT_GOLDEN_HORSESHOE`
---|`ARTIFACT_WAYFARER_BOOTS`
---|`ARTIFACT_BOOTS_OF_INTERFERENCE`
---|`ARTIFACT_ENDLESS_SACK_OF_GOLD`
---|`ARTIFACT_ENDLESS_BAG_OF_GOLD`
---|`ARTIFACT_ANGEL_WINGS`
---|`ARTIFACT_LION_HIDE_CAPE`
---|`ARTIFACT_PHOENIX_FEATHER_CAPE`
---|`ARTIFACT_CLOAK_OF_MOURNING`
---|`ARTIFACT_HELM_OF_ENLIGHTMENT`
---|`ARTIFACT_CHAIN_MAIL_OF_ENLIGHTMENT`
---|`ARTIFACT_DRAGON_SCALE_ARMOR`
---|`ARTIFACT_DRAGON_SCALE_SHIELD`
---|`ARTIFACT_DRAGON_BONE_GRAVES`
---|`ARTIFACT_DRAGON_WING_MANTLE`
---|`ARTIFACT_DRAGON_TEETH_NECKLACE`
---|`ARTIFACT_DRAGON_TALON_CROWN`
---|`ARTIFACT_DRAGON_EYE_RING`
---|`ARTIFACT_DRAGON_FLAME_TONGUE`
---|`ARTIFACT_ROBE_OF_MAGI`
---|`ARTIFACT_STAFF_OF_MAGI`
---|`ARTIFACT_CROWN_OF_MAGI`
---|`ARTIFACT_RING_OF_MAGI`
---|`ARTIFACT_DWARVEN_MITHRAL_CUIRASS`
---|`ARTIFACT_DWARVEN_MITHRAL_GREAVES`
---|`ARTIFACT_DWARVEN_MITHRAL_HELMET`
---|`ARTIFACT_DWARVEN_MITHRAL_SHIELD`
---|`ARTIFACT_SCROLL_OF_SPELL_X`
---|`ARTIFACT_GRAAL`
---|`ARTIFACT_BOOTS_OF_LEVITATION`
---|`ARTIFACT_SKULL_HELMET`
---|`ARTIFACT_VALORIOUS_ARMOR`
---|`ARTIFACT_BOOTS_OF_SWIFTNESS`
---|`ARTIFACT_MOONBLADE`
---|`ARTIFACT_RING_OF_CELERITY`
---|`ARTIFACT_BAND_OF_CONJURER`
---|`ARTIFACT_EARTHSLIDERS`
---|`ARTIFACT_RIGID_MANTLE`
---|`ARTIFACT_JINXING_BAND`
---|`ARTIFACT_BONESTUDDED_LEATHER`
---|`ARTIFACT_WISPERING_RING`
---|`ARTIFACT_HELM_OF_CHAOS`
---|`ARTIFACT_TWISTING_NEITHER`
---|`ARTIFACT_SANDALS_OF_THE_SAINT`
---|`ARTIFACT_SHAWL_OF_GREAT_LICH`
---|`ARTIFACT_RING_OF_DEATH`
---|`ARTIFACT_NECROMANCER_PENDANT`
---|`ARTIFACT_FREIDA`
---|`ARTIFACT_RING_OF_THE_SHADOWBRAND`
---|`ARTIFACT_OGRE_CLUB`
---|`ARTIFACT_OGRE_SHIELD`
---|`ARTIFACT_TOME_OF_DESTRUCTION`
---|`ARTIFACT_TOME_OF_LIGHT_MAGIC`
---|`ARTIFACT_TOME_OF_DARK_MAGIC`
---|`ARTIFACT_TOME_OF_SUMMONING_MAGIC`
---|`ARTIFACT_BEGINNER_MAGIC_STICK`
---|`ARTIFACT_RUNIC_WAR_AXE`
---|`ARTIFACT_RUNIC_WAR_HARNESS`
---|`ARTIFACT_SKULL_OF_MARKAL`
---|`ARTIFACT_BEARHIDE_WRAPS`
---|`ARTIFACT_DWARVEN_SMITHY_HUMMER`
---|`ARTIFACT_RUNE_OF_FLAME`
---|`ARTIFACT_TAROT_DECK`
---|`ARTIFACT_CROWN_OF_LEADER`
---|`ARTIFACT_MASK_OF_DOPPELGANGER`
---|`ARTIFACT_EDGE_OF_BALANCE`
---|`ARTIFACT_RING_OF_MACHINE_AFFINITY`
---|`ARTIFACT_HORN_OF_PLENTY`
---|`ARTIFACT_RING_OF_UNSUMMONING`
---|`ARTIFACT_BOOK_OF_POWER`
---|`ARTIFACT_TREEBORN_QUIVER`
---|`ARTIFACT_PRINCESS`
ARTIFACT_SWORD_OF_RUINS = 1
ARTIFACT_GREAT_AXE_OF_GIANT_SLAYING = 2
ARTIFACT_WAND_OF_X = 3
ARTIFACT_UNICORN_HORN_BOW = 4
ARTIFACT_TITANS_TRIDENT = 5
ARTIFACT_STAFF_OF_VEXINGS = 6
ARTIFACT_SHACKLES_OF_WAR = 7
ARTIFACT_FOUR_LEAF_CLOVER = 8
ARTIFACT_ICEBERG_SHIELD = 9
ARTIFACT_GOLDEN_SEXTANT = 10
ARTIFACT_CROWN_OF_COURAGE = 11
ARTIFACT_CROWN_OF_MANY_EYES = 12
ARTIFACT_PLATE_MAIL_OF_STABILITY = 13
ARTIFACT_BREASTPLATE_OF_PETRIFIED_WOOD = 14
ARTIFACT_PEDANT_OF_MASTERY = 15
ARTIFACT_NECKLACE_OF_BRAVERY = 16
ARTIFACT_WEREWOLF_CLAW_NECKLACE = 17
ARTIFACT_EVERCOLD_ICICLE = 18
ARTIFACT_NECKLACE_OF_POWER = 19
ARTIFACT_RING_OF_LIGHTING_PROTECTION = 20
ARTIFACT_RING_OF_LIFE = 21
ARTIFACT_RING_OF_HASTE = 22
ARTIFACT_NIGHTMARISH_RING = 23
ARTIFACT_BOOTS_OF_SPEED = 24
ARTIFACT_GOLDEN_HORSESHOE = 25
ARTIFACT_WAYFARER_BOOTS = 26
ARTIFACT_BOOTS_OF_INTERFERENCE = 27
ARTIFACT_ENDLESS_SACK_OF_GOLD = 28
ARTIFACT_ENDLESS_BAG_OF_GOLD = 29
ARTIFACT_ANGEL_WINGS = 30
ARTIFACT_LION_HIDE_CAPE = 31
ARTIFACT_PHOENIX_FEATHER_CAPE = 32
ARTIFACT_CLOAK_OF_MOURNING = 33
ARTIFACT_HELM_OF_ENLIGHTMENT = 34
ARTIFACT_CHAIN_MAIL_OF_ENLIGHTMENT = 35
ARTIFACT_DRAGON_SCALE_ARMOR = 36
ARTIFACT_DRAGON_SCALE_SHIELD = 37
ARTIFACT_DRAGON_BONE_GRAVES = 38
ARTIFACT_DRAGON_WING_MANTLE = 39
ARTIFACT_DRAGON_TEETH_NECKLACE = 40
ARTIFACT_DRAGON_TALON_CROWN = 41
ARTIFACT_DRAGON_EYE_RING = 42
ARTIFACT_DRAGON_FLAME_TONGUE = 43
ARTIFACT_ROBE_OF_MAGI = 44
ARTIFACT_STAFF_OF_MAGI = 45
ARTIFACT_CROWN_OF_MAGI = 46
ARTIFACT_RING_OF_MAGI = 47
ARTIFACT_DWARVEN_MITHRAL_CUIRASS = 48
ARTIFACT_DWARVEN_MITHRAL_GREAVES = 49
ARTIFACT_DWARVEN_MITHRAL_HELMET = 50
ARTIFACT_DWARVEN_MITHRAL_SHIELD = 51
ARTIFACT_SCROLL_OF_SPELL_X = 52
ARTIFACT_GRAAL = 53
ARTIFACT_BOOTS_OF_LEVITATION = 54
ARTIFACT_SKULL_HELMET = 55
ARTIFACT_VALORIOUS_ARMOR = 56
ARTIFACT_BOOTS_OF_SWIFTNESS = 57
ARTIFACT_MOONBLADE = 58
ARTIFACT_RING_OF_CELERITY = 59
ARTIFACT_BAND_OF_CONJURER = 60
ARTIFACT_EARTHSLIDERS = 61
ARTIFACT_RIGID_MANTLE = 62
ARTIFACT_JINXING_BAND = 63
ARTIFACT_BONESTUDDED_LEATHER = 64
ARTIFACT_WISPERING_RING = 65
ARTIFACT_HELM_OF_CHAOS = 66
ARTIFACT_TWISTING_NEITHER = 67
ARTIFACT_SANDALS_OF_THE_SAINT = 68
ARTIFACT_SHAWL_OF_GREAT_LICH = 69
ARTIFACT_RING_OF_DEATH = 70
ARTIFACT_NECROMANCER_PENDANT = 71
ARTIFACT_FREIDA = 72
ARTIFACT_RING_OF_THE_SHADOWBRAND = 73
ARTIFACT_OGRE_CLUB = 74
ARTIFACT_OGRE_SHIELD = 75
ARTIFACT_TOME_OF_DESTRUCTION = 76
ARTIFACT_TOME_OF_LIGHT_MAGIC = 77
ARTIFACT_TOME_OF_DARK_MAGIC = 78
ARTIFACT_TOME_OF_SUMMONING_MAGIC = 79
ARTIFACT_BEGINNER_MAGIC_STICK = 80
ARTIFACT_RUNIC_WAR_AXE = 81
ARTIFACT_RUNIC_WAR_HARNESS = 82
ARTIFACT_SKULL_OF_MARKAL = 83
ARTIFACT_BEARHIDE_WRAPS = 84
ARTIFACT_DWARVEN_SMITHY_HUMMER = 85
ARTIFACT_RUNE_OF_FLAME = 86
ARTIFACT_TAROT_DECK = 87
ARTIFACT_CROWN_OF_LEADER = 88
ARTIFACT_MASK_OF_DOPPELGANGER = 89
ARTIFACT_EDGE_OF_BALANCE = 90
ARTIFACT_RING_OF_MACHINE_AFFINITY = 91
ARTIFACT_HORN_OF_PLENTY = 92
ARTIFACT_RING_OF_UNSUMMONING = 93
ARTIFACT_BOOK_OF_POWER = 94
ARTIFACT_TREEBORN_QUIVER = 95
ARTIFACT_PRINCESS = 96