---@alias TownType
---|`TOWN_NO_TYPE`
---|`TOWN_HEAVEN`
---|`TOWN_PRESERVE`
---|`TOWN_ACADEMY`
---|`TOWN_DUNGEON`
---|`TOWN_NECROMANCY`
---|`TOWN_INFERNO`
---|`TOWN_FORTRESS`
---|`TOWN_STRONGHOLD`
TOWN_NO_TYPE = - 1
TOWN_HEAVEN = 0
TOWN_PRESERVE = 1
TOWN_ACADEMY = 2
TOWN_DUNGEON = 3
TOWN_NECROMANCY = 4
TOWN_INFERNO = 5
TOWN_FORTRESS = 6
TOWN_STRONGHOLD = 7

---@alias HeroStatType
---|`STAT_EXPERIENCE`
---|`STAT_ATTACK`
---|`STAT_DEFENCE`
---|`STAT_SPELL_POWER`
---|`STAT_KNOWLEDGE`
---|`STAT_LUCK`
---|`STAT_MORALE`
---|`STAT_MOVE_POINTS`
---|`STAT_MANA_POINTS`
STAT_EXPERIENCE = 0
STAT_ATTACK = 1
STAT_DEFENCE = 2
STAT_SPELL_POWER = 3
STAT_KNOWLEDGE = 4
STAT_LUCK = 5
STAT_MORALE = 6
STAT_MOVE_POINTS = 7
STAT_MANA_POINTS = 8

---@alias ResourceType
---|`WOOD`
---|`ORE`
---|`MERCURY`
---|`CRYSTAL`
---|`SULFUR`
---|`GEM`
---|`GOLD`
---|`WOOD`
WOOD    = 0
ORE     = 1
MERCURY = 2
CRYSTAL = 3
SULFUR  = 4
GEM     = 5
GOLD    = 6

---@alias ObjectiveStateType
---|`OBJECTIVE_SCENARIO_INFO`
---|`OBJECTIVE_UNKNOWN`
---|`OBJECTIVE_ACTIVE`
---|`OBJECTIVE_COMPLETED`
---|`OBJECTIVE_FAILED`
OBJECTIVE_SCENARIO_INFO = 0
OBJECTIVE_UNKNOWN = 1
OBJECTIVE_ACTIVE = 2
OBJECTIVE_COMPLETED = 3
OBJECTIVE_FAILED = 4

---@alias ObjectInteractionCursorType
---|`DISABLED_DEFAULT`
---|`DISABLED_ATTACK`
---|`DISABLED_INTERACT`
---|`DISABLED_BLOCKED`
DISABLED_DEFAULT = 0
DISABLED_ATTACK = 1
DISABLED_INTERACT = 2
DISABLED_BLOCKED = 3

---@alias MapLevel
---|`GROUND` # верхний уровень
---|`UNDERGROUND` # нижний уровень
GROUND = 0
UNDERGROUND = 1

---@alias PlayerID
---|`PLAYER_NONE` # 0
---|`PLAYER_1` # 1
---|`PLAYER_2` # 2
---|`PLAYER_3` # 3
---|`PLAYER_4` # 4
---|`PLAYER_5` # 5
---|`PLAYER_6` # 6
---|`PLAYER_7` # 7
---|`PLAYER_8` # 8
PLAYER_NONE = 0
PLAYER_1 = 1
PLAYER_2 = 2
PLAYER_3 = 3
PLAYER_4 = 4
PLAYER_5 = 5
PLAYER_6 = 6
PLAYER_7 = 7
PLAYER_8 = 8

---@alias AnimationActionType
--- |`IDLE` # анимация проигрывается постоянно
--- |`ONESHOT` # анимация проигрывается один раз
--- |`ONESHOT_STILL` # анимация проигрывается и застывает в финальном кадре
--- |`NON_ESSENTIAL` # аналогично ONESHOT, однако, любая другая анимация прервет проигрывание этой
IDLE = 1
ONESHOT_STILL = 2
ONESHOT = 3
NON_ESSENTIAL = 5

---@alias PlayerGameState
---|`PLAYER_NOT_IN_GAME`
---|`PLAYER_ACTIVE`
---|`PLAYER_WON`
---|`PLAYER_LOST`
PLAYER_NOT_IN_GAME = 0
PLAYER_ACTIVE = 1
PLAYER_WON = 2
PLAYER_LOST = 3

---@alias TreasureKind
---|`TREASURE_CRYSTAL`
---|`TREASURE_GEMS`
---|`TREASURE_GOLD`
---|`TREASURE_MERCURY`
---|`TREASURE_ORE`
---|`TREASURE_SULFUR`
---|`TREASURE_WOOD`
---|`TREASURE_CAMPFIRE`
---|`TREASURE_CHEST`
---|`TREASURE_SEA_CHEST`
---|`TREASURE_FLOATSAM`
---|`TREASURE_SHIPWRECK`
TREASURE_CRYSTAL   = 0
TREASURE_GEMS      = 1
TREASURE_GOLD      = 2
TREASURE_MERCURY   = 3
TREASURE_ORE       = 4
TREASURE_SULFUR    = 5
TREASURE_WOOD      = 6
TREASURE_CAMPFIRE  = 8
TREASURE_CHEST     = 9
TREASURE_SEA_CHEST = 10
TREASURE_FLOATSAM  = 11
TREASURE_SHIPWRECK = 13

---@alias DateType
---|`DAY`
---|`WEEK`
---|`MONTH`
---|`DAY_OF_WEEK`
---|`ABSOLUTE_DAY`
DAY = 0
WEEK = 1
MONTH = 2
DAY_OF_WEEK = 3
ABSOLUTE_DAY = DAY

---@alias MonsterMoodType
---|`MONSTER_MOOD_FRIENDLY`
---|`MONSTER_MOOD_AGGRESSIVE`
---|`MONSTER_MOOD_HOSTILE`
---|`MONSTER_MOOD_WILD`
MONSTER_MOOD_FRIENDLY = 0
MONSTER_MOOD_AGGRESSIVE = 1
MONSTER_MOOD_HOSTILE = 2
MONSTER_MOOD_WILD = 3

---@alias MonsterCourageType
---|`MONSTER_COURAGE_ALWAYS_JOIN`
---|`MONSTER_COURAGE_ALWAYS_FIGHT`
---|`MONSTER_COURAGE_CAN_FLEE_JOIN`
MONSTER_COURAGE_ALWAYS_JOIN = 0
MONSTER_COURAGE_ALWAYS_FIGHT = 1
MONSTER_COURAGE_CAN_FLEE_JOIN = 2

---@alias BorderguardKeyColor
---|`RED_KEY`
---|`BLUE_KEY`
---|`GREEN_KEY`
---|`YELLOW_KEY`
---|`ORANGE_KEY`
---|`TEAL_KEY`
---|`PURPLE_KEY`
---|`TAN_KEY`
RED_KEY = 1
BLUE_KEY = 2
GREEN_KEY = 3
YELLOW_KEY = 4
ORANGE_KEY = 5
TEAL_KEY = 6
PURPLE_KEY = 7
TAN_KEY = 8

---@alias TriggerType
---|`NEW_DAY_TRIGGER`
---|`PLAYER_ADD_HERO_TRIGGER`
---|`PLAYER_REMOVE_HERO_TRIGGER`
---|`OBJECTIVE_STATE_CHANGE_TRIGGER`
---|`OBJECT_TOUCH_TRIGGER`
---|`OBJECT_CAPTURE_TRIGGER`
---|`REGION_ENTER_AND_STOP_TRIGGER`
---|`REGION_ENTER_WITHOUT_STOP_TRIGGER`
---|`HERO_LEVELUP_TRIGGER`
---|`WAR_FOG_ENTER_TRIGGER`
---|`COMBAT_RESULTS_TRIGGER`
---|`CUSTOM_ABILITY_TRIGGER`
---|`REGION_EXIT_TRIGGER`
---|`HERO_ADD_SKILL_TRIGGER`
---|`HERO_REMOVE_SKILL_TRIGGER`
---|`HERO_TOUCH_TRIGGER`
NEW_DAY_TRIGGER = 0
PLAYER_ADD_HERO_TRIGGER = 1
PLAYER_REMOVE_HERO_TRIGGER = 2
OBJECTIVE_STATE_CHANGE_TRIGGER = 3
OBJECT_TOUCH_TRIGGER = 4
OBJECT_CAPTURE_TRIGGER = 5
REGION_ENTER_AND_STOP_TRIGGER = 6
REGION_ENTER_WITHOUT_STOP_TRIGGER = 7
HERO_LEVELUP_TRIGGER = 8
WAR_FOG_ENTER_TRIGGER = 9
COMBAT_RESULTS_TRIGGER = 11
CUSTOM_ABILITY_TRIGGER = 12
REGION_EXIT_TRIGGER = 13
HERO_ADD_SKILL_TRIGGER = 14
HERO_REMOVE_SKILL_TRIGGER = 15
HERO_TOUCH_TRIGGER = 16

---@alias SavedCombatResultType
---|`COMBAT_RESULT_NONE`
---|`COMBAT_RESULT_WIN`
---|`COMBAT_RESULT_RETREAT`
---|`COMBAT_RESULT_SURRENDER`
COMBAT_RESULT_NONE = 0
COMBAT_RESULT_WIN = 1
COMBAT_RESULT_RETREAT = 2
COMBAT_RESULT_SURRENDER = 3

---@alias CustomAbilityId
---|`CUSTOM_ABILITY_1`
---|`CUSTOM_ABILITY_2`
---|`CUSTOM_ABILITY_3`
---|`CUSTOM_ABILITY_4`
CUSTOM_ABILITY_1 = 1
CUSTOM_ABILITY_2 = 2
CUSTOM_ABILITY_3 = 3
CUSTOM_ABILITY_4 = 4

---@alias CustomAbilityMode
---|`CUSTOM_ABILITY_NOT_PRESENT`
---|`CUSTOM_ABILITY_DISABLED`
---|`CUSTOM_ABILITY_ENABLED`
CUSTOM_ABILITY_NOT_PRESENT = -1
CUSTOM_ABILITY_DISABLED = 0
CUSTOM_ABILITY_ENABLED = 1

---@alias MonsterNameFilter
---|`MONSTER_NAME_SINGLE`
---|`MONSTER_NAME_MULTIPLE`
---|`MONSTER_NAMES_ALL`
MONSTER_NAME_SINGLE = 0
MONSTER_NAME_MULTIPLE = 1
MONSTER_NAMES_ALL = 2

---@alias RegionAutoActionMode
---|`REGION_AUTOACTION_ON_ENTER`
---|`REGION_AUTOACTION_ON_EXIT`
REGION_AUTOACTION_ON_ENTER = 1
REGION_AUTOACTION_ON_EXIT = 2

---@alias RegionAutoActionEnableVariant
---|`REGION_AUTOACTION_OBJECT_NO_ACTION`
---|`REGION_AUTOACTION_OBJECT_DISABLE`
---|`REGION_AUTOACTION_OBJECT_ENABLE`
REGION_AUTOACTION_OBJECT_NO_ACTION = -1
REGION_AUTOACTION_OBJECT_DISABLE = 0
REGION_AUTOACTION_OBJECT_ENABLE = 1

---@alias HeroRoleMode
---|`HERO_ROLE_MODE_REGULAR`
---|`HERO_ROLE_MODE_FREEMAN`
---|`HERO_ROLE_MODE_HERMIT`
HERO_ROLE_MODE_REGULAR = 0
HERO_ROLE_MODE_FREEMAN = 1	
HERO_ROLE_MODE_HERMIT  = 2

---@alias PlayerFilter
---|`PLAYERFLT_1`
---|`PLAYERFLT_2`
---|`PLAYERFLT_3`
---|`PLAYERFLT_4`
---|`PLAYERFLT_5`
---|`PLAYERFLT_6`
---|`PLAYERFLT_7`
---|`PLAYERFLT_8`
---|`PLAYERFLT_ALL`
PLAYERFLT_1 = 1
PLAYERFLT_2 = 2
PLAYERFLT_3 = 4
PLAYERFLT_4 = 8
PLAYERFLT_5 = 16
PLAYERFLT_6 = 32
PLAYERFLT_7 = 64
PLAYERFLT_8 = 128
PLAYERFLT_ALL = 255

---@alias PlayerTeamFilter
---|`PLAYERFLT_TEAM_1`
---|`PLAYERFLT_TEAM_2`
---|`PLAYERFLT_TEAM_3`
---|`PLAYERFLT_TEAM_4`
---|`PLAYERFLT_TEAM_5`
---|`PLAYERFLT_TEAM_6`
---|`PLAYERFLT_TEAM_7`
---|`PLAYERFLT_TEAM_8`
PLAYERFLT_TEAM_1 = -1
PLAYERFLT_TEAM_2 = -2
PLAYERFLT_TEAM_3 = -3
PLAYERFLT_TEAM_4 = -4
PLAYERFLT_TEAM_5 = -5
PLAYERFLT_TEAM_6 = -6
PLAYERFLT_TEAM_7 = -7
PLAYERFLT_TEAM_8 = -8

---@alias PlayerTeam
---|`PLAYERS_TEAM_1`
---|`PLAYERS_TEAM_2`
---|`PLAYERS_TEAM_3`
---|`PLAYERS_TEAM_4`
---|`PLAYERS_TEAM_5`
---|`PLAYERS_TEAM_6`
---|`PLAYERS_TEAM_7`
---|`PLAYERS_TEAM_8`
PLAYERS_TEAM_1 = 1
PLAYERS_TEAM_2 = 2
PLAYERS_TEAM_3 = 3
PLAYERS_TEAM_4 = 4
PLAYERS_TEAM_5 = 5
PLAYERS_TEAM_6 = 6
PLAYERS_TEAM_7 = 7
PLAYERS_TEAM_8 = 8

---@alias HeroBattleBonusType
---|`HERO_BATTLE_BONUS_LUCK`
---|`HERO_BATTLE_BONUS_MORALE`
---|`HERO_BATTLE_BONUS_ATTACK`
---|`HERO_BATTLE_BONUS_DEFENCE`
---|`HERO_BATTLE_BONUS_HITPOINTS`
---|`HERO_BATTLE_BONUS_INITIATIVE`
---|`HERO_BATTLE_BONUS_SPEED`
HERO_BATTLE_BONUS_LUCK = 0
HERO_BATTLE_BONUS_MORALE = 1
HERO_BATTLE_BONUS_ATTACK = 2
HERO_BATTLE_BONUS_DEFENCE = 3
HERO_BATTLE_BONUS_HITPOINTS = 4
HERO_BATTLE_BONUS_INITIATIVE = 5
HERO_BATTLE_BONUS_SPEED = 6

---@alias ArtifactSetType
---|`ARTIFACT_SET_DRAGONISH`
---|`ARTIFACT_SET_DWARVEN`
---|`ARTIFACT_SET_LIONS`
---|`ARTIFACT_SET_MAGIS`
---|`ARTIFACT_SET_NECROMANCERS`
---|`ARTIFACT_SET_EDUCATIONAL`
---|`ARTIFACT_SET_HUNTERS`
---|`ARTIFACT_SET_OGRES`
---|`ARTIFACT_SET_RUNIC`
---|`ARTIFACT_SET_DEMONIC`
ARTIFACT_SET_DRAGONISH = 0
ARTIFACT_SET_DWARVEN = 1
ARTIFACT_SET_LIONS = 2
ARTIFACT_SET_MAGIS = 3
ARTIFACT_SET_NECROMANCERS = 4
ARTIFACT_SET_EDUCATIONAL = 5
ARTIFACT_SET_HUNTERS = 6
ARTIFACT_SET_OGRES = 7
ARTIFACT_SET_RUNIC = 8
ARTIFACT_SET_DEMONIC = 9

---@alias MasteryLevel
---|`MASTERY_NONE`
---|`MASTERY_BASIC`
---|`MASTERY_ADVANCED`
---|`MASTERY_EXPERT`
---|`MASTERY_EXTRA_EXPERT`
MASTERY_NONE = 0
MASTERY_BASIC = 1
MASTERY_ADVANCED = 2
MASTERY_EXPERT = 3
MASTERY_EXTRA_EXPERT = 4

---@alias WarMachineType
---|`WAR_MACHINE_BALLISTA`
---|`WAR_MACHINE_CATAPULT`
---|`WAR_MACHINE_FIRST_AID_TENT`
---|`WAR_MACHINE_AMMO_CART`
WAR_MACHINE_BALLISTA = 1
WAR_MACHINE_CATAPULT = 2
WAR_MACHINE_FIRST_AID_TENT = 3
WAR_MACHINE_AMMO_CART = 4

---@alias DifficultyLevel
---|`DIFFICULTY_EASY`
---|`DIFFICULTY_NORMAL`
---|`DIFFICULTY_HARD`
---|`DIFFICULTY_HEROIC`
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2
DIFFICULTY_HEROIC = 3