---@alias CreatureID
---|`CREATURE_UNKNOWN`
---|`CREATURE_PEASANT`
---|`CREATURE_MILITIAMAN`
---|`CREATURE_ARCHER`
---|`CREATURE_MARKSMAN`
---|`CREATURE_FOOTMAN`
---|`CREATURE_SWORDSMAN`
---|`CREATURE_GRIFFIN`
---|`CREATURE_ROYAL_GRIFFIN`
---|`CREATURE_PRIEST`
---|`CREATURE_CLERIC`
---|`CREATURE_CAVALIER`
---|`CREATURE_PALADIN`
---|`CREATURE_ANGEL`
---|`CREATURE_ARCHANGEL`
---|`CREATURE_FAMILIAR`
---|`CREATURE_IMP`
---|`CREATURE_DEMON`
---|`CREATURE_HORNED_DEMON`
---|`CREATURE_HELL_HOUND`
---|`CREATURE_CERBERI`
---|`CREATURE_SUCCUBUS`
---|`CREATURE_INFERNAL_SUCCUBUS`
---|`CREATURE_NIGHTMARE`
---|`CREATURE_FRIGHTFUL_NIGHTMARE`
---|`CREATURE_PIT_FIEND`
---|`CREATURE_BALOR`
---|`CREATURE_DEVIL`
---|`CREATURE_ARCHDEVIL`
---|`CREATURE_SKELETON`
---|`CREATURE_SKELETON_ARCHER`
---|`CREATURE_WALKING_DEAD`
---|`CREATURE_ZOMBIE`
---|`CREATURE_MANES`
---|`CREATURE_GHOST`
---|`CREATURE_VAMPIRE`
---|`CREATURE_VAMPIRE_LORD`
---|`CREATURE_LICH`
---|`CREATURE_DEMILICH`
---|`CREATURE_WIGHT`
---|`CREATURE_WRAITH`
---|`CREATURE_BONE_DRAGON`
---|`CREATURE_SHADOW_DRAGON`
---|`CREATURE_PIXIE`
---|`CREATURE_SPRITE`
---|`CREATURE_BLADE_JUGGLER`
---|`CREATURE_WAR_DANCER`
---|`CREATURE_WOOD_ELF`
---|`CREATURE_GRAND_ELF`
---|`CREATURE_DRUID`
---|`CREATURE_DRUID_ELDER`
---|`CREATURE_UNICORN`
---|`CREATURE_WAR_UNICORN`
---|`CREATURE_TREANT`
---|`CREATURE_TREANT_GUARDIAN`
---|`CREATURE_GREEN_DRAGON`
---|`CREATURE_GOLD_DRAGON`
---|`CREATURE_GREMLIN`
---|`CREATURE_MASTER_GREMLIN`
---|`CREATURE_STONE_GARGOYLE`
---|`CREATURE_OBSIDIAN_GARGOYLE`
---|`CREATURE_IRON_GOLEM`
---|`CREATURE_STEEL_GOLEM`
---|`CREATURE_MAGI`
---|`CREATURE_ARCH_MAGI`
---|`CREATURE_GENIE`
---|`CREATURE_MASTER_GENIE`
---|`CREATURE_RAKSHASA`
---|`CREATURE_RAKSHASA_RUKH`
---|`CREATURE_GIANT`
---|`CREATURE_TITAN`
---|`CREATURE_SCOUT`
---|`CREATURE_ASSASSIN`
---|`CREATURE_WITCH`
---|`CREATURE_BLOOD_WITCH`
---|`CREATURE_MINOTAUR`
---|`CREATURE_MINOTAUR_KING`
---|`CREATURE_RIDER`
---|`CREATURE_RAVAGER`
---|`CREATURE_HYDRA`
---|`CREATURE_CHAOS_HYDRA`
---|`CREATURE_MATRON`
---|`CREATURE_MATRIARCH`
---|`CREATURE_DEEP_DRAGON`
---|`CREATURE_BLACK_DRAGON`
---|`CREATURE_FIRE_ELEMENTAL`
---|`CREATURE_WATER_ELEMENTAL`
---|`CREATURE_EARTH_ELEMENTAL`
---|`CREATURE_AIR_ELEMENTAL`
---|`CREATURE_DEATH_KNIGHT`
---|`CREATURE_PHOENIX`
---|`CREATURE_DEFENDER`
---|`CREATURE_STOUT_DEFENDER`
---|`CREATURE_AXE_FIGHTER`
---|`CREATURE_AXE_THROWER`
---|`CREATURE_BEAR_RIDER`
---|`CREATURE_BLACKBEAR_RIDER`
---|`CREATURE_BROWLER`
---|`CREATURE_BERSERKER`
---|`CREATURE_RUNE_MAGE`
---|`CREATURE_FLAME_MAGE`
---|`CREATURE_THANE`
---|`CREATURE_WARLORD`
---|`CREATURE_FIRE_DRAGON`
---|`CREATURE_MAGMA_DRAGON`
---|`CREATURE_LANDLORD`
---|`CREATURE_LONGBOWMAN`
---|`CREATURE_VINDICATOR`
---|`CREATURE_BATTLE_GRIFFIN`
---|`CREATURE_ZEALOT`
---|`CREATURE_CHAMPION`
---|`CREATURE_SERAPH`
---|`CREATURE_WOLF`
---|`CREATURE_SNOW_APE`
---|`CREATURE_MANTICORE`
---|`CREATURE_MUMMY`
---|`CREATURE_GOBLIN`
---|`CREATURE_GOBLIN_TRAPPER`
---|`CREATURE_CENTAUR`
---|`CREATURE_CENTAUR_NOMAD`
---|`CREATURE_ORC_WARRIOR`
---|`CREATURE_ORC_SLAYER`
---|`CREATURE_SHAMAN`
---|`CREATURE_SHAMAN_WITCH`
---|`CREATURE_ORCCHIEF_BUTCHER`
---|`CREATURE_ORCCHIEF_EXECUTIONER`
---|`CREATURE_WYVERN`
---|`CREATURE_WYVERN_POISONOUS`
---|`CREATURE_CYCLOP`
---|`CREATURE_CYCLOP_UNTAMED`
---|`CREATURE_QUASIT`
---|`CREATURE_HORNED_LEAPER`
---|`CREATURE_FIREBREATHER_HOUND`
---|`CREATURE_SUCCUBUS_SEDUCER`
---|`CREATURE_HELLMARE`
---|`CREATURE_PIT_SPAWN`
---|`CREATURE_ARCH_DEMON`
---|`CREATURE_STALKER`
---|`CREATURE_BLOOD_WITCH_2`
---|`CREATURE_MINOTAUR_CAPTAIN`
---|`CREATURE_BLACK_RIDER`
---|`CREATURE_ACIDIC_HYDRA`
---|`CREATURE_SHADOW_MISTRESS`
---|`CREATURE_RED_DRAGON`
---|`CREATURE_DRYAD`
---|`CREATURE_BLADE_SINGER`
---|`CREATURE_SHARP_SHOOTER`
---|`CREATURE_HIGH_DRUID`
---|`CREATURE_WHITE_UNICORN`
---|`CREATURE_ANGER_TREANT`
---|`CREATURE_RAINBOW_DRAGON`
---|`CREATURE_SKELETON_WARRIOR`
---|`CREATURE_DISEASE_ZOMBIE`
---|`CREATURE_POLTERGEIST`
---|`CREATURE_NOSFERATU`
---|`CREATURE_LICH_MASTER`
---|`CREATURE_BANSHEE`
---|`CREATURE_HORROR_DRAGON`
---|`CREATURE_GREMLIN_SABOTEUR`
---|`CREATURE_MARBLE_GARGOYLE`
---|`CREATURE_OBSIDIAN_GOLEM`
---|`CREATURE_COMBAT_MAGE`
---|`CREATURE_DJINN_VIZIER`
---|`CREATURE_RAKSHASA_KSHATRI`
---|`CREATURE_STORM_LORD`
---|`CREATURE_STONE_DEFENDER`
---|`CREATURE_HARPOONER`
---|`CREATURE_WHITE_BEAR_RIDER`
---|`CREATURE_BATTLE_RAGER`
---|`CREATURE_FLAME_KEEPER`
---|`CREATURE_THUNDER_THANE`
---|`CREATURE_LAVA_DRAGON`
---|`CREATURE_GOBLIN_DEFILER`
---|`CREATURE_CENTAUR_MARADEUR`
---|`CREATURE_ORC_WARMONGER`
---|`CREATURE_SHAMAN_HAG`
---|`CREATURE_ORCCHIEF_CHIEFTAIN`
---|`CREATURE_WYVERN_PAOKAI`
---|`CREATURE_CYCLOP_BLOODEYED`
CREATURE_UNKNOWN = 0
CREATURE_PEASANT = 1
CREATURE_MILITIAMAN = 2
CREATURE_ARCHER = 3
CREATURE_MARKSMAN = 4
CREATURE_FOOTMAN = 5
CREATURE_SWORDSMAN = 6
CREATURE_GRIFFIN = 7
CREATURE_ROYAL_GRIFFIN = 8
CREATURE_PRIEST = 9
CREATURE_CLERIC = 10
CREATURE_CAVALIER = 11
CREATURE_PALADIN = 12
CREATURE_ANGEL = 13
CREATURE_ARCHANGEL = 14
CREATURE_FAMILIAR = 15
CREATURE_IMP = 16
CREATURE_DEMON = 17
CREATURE_HORNED_DEMON = 18
CREATURE_HELL_HOUND = 19
CREATURE_CERBERI = 20
CREATURE_SUCCUBUS = 21
CREATURE_INFERNAL_SUCCUBUS = 22
CREATURE_NIGHTMARE = 23
CREATURE_FRIGHTFUL_NIGHTMARE = 24
CREATURE_PIT_FIEND = 25
CREATURE_BALOR = 26
CREATURE_DEVIL = 27
CREATURE_ARCHDEVIL = 28
CREATURE_SKELETON = 29
CREATURE_SKELETON_ARCHER = 30
CREATURE_WALKING_DEAD = 31
CREATURE_ZOMBIE = 32
CREATURE_MANES = 33
CREATURE_GHOST = 34
CREATURE_VAMPIRE = 35
CREATURE_VAMPIRE_LORD = 36
CREATURE_LICH = 37
CREATURE_DEMILICH = 38
CREATURE_WIGHT = 39
CREATURE_WRAITH = 40
CREATURE_BONE_DRAGON = 41
CREATURE_SHADOW_DRAGON = 42
CREATURE_PIXIE = 43
CREATURE_SPRITE = 44
CREATURE_BLADE_JUGGLER = 45
CREATURE_WAR_DANCER = 46
CREATURE_WOOD_ELF = 47
CREATURE_GRAND_ELF = 48
CREATURE_DRUID = 49
CREATURE_DRUID_ELDER = 50
CREATURE_UNICORN = 51
CREATURE_WAR_UNICORN = 52
CREATURE_TREANT = 53
CREATURE_TREANT_GUARDIAN = 54
CREATURE_GREEN_DRAGON = 55
CREATURE_GOLD_DRAGON = 56
CREATURE_GREMLIN = 57
CREATURE_MASTER_GREMLIN = 58
CREATURE_STONE_GARGOYLE = 59
CREATURE_OBSIDIAN_GARGOYLE = 60
CREATURE_IRON_GOLEM = 61
CREATURE_STEEL_GOLEM = 62
CREATURE_MAGI = 63
CREATURE_ARCH_MAGI = 64
CREATURE_GENIE = 65
CREATURE_MASTER_GENIE = 66
CREATURE_RAKSHASA = 67
CREATURE_RAKSHASA_RUKH = 68
CREATURE_GIANT = 69
CREATURE_TITAN = 70
CREATURE_SCOUT = 71
CREATURE_ASSASSIN = 72
CREATURE_WITCH = 73
CREATURE_BLOOD_WITCH = 74
CREATURE_MINOTAUR = 75
CREATURE_MINOTAUR_KING = 76
CREATURE_RIDER = 77
CREATURE_RAVAGER = 78
CREATURE_HYDRA = 79
CREATURE_CHAOS_HYDRA = 80
CREATURE_MATRON = 81
CREATURE_MATRIARCH = 82
CREATURE_DEEP_DRAGON = 83
CREATURE_BLACK_DRAGON = 84
CREATURE_FIRE_ELEMENTAL = 85
CREATURE_WATER_ELEMENTAL = 86
CREATURE_EARTH_ELEMENTAL = 87
CREATURE_AIR_ELEMENTAL = 88
CREATURE_DEATH_KNIGHT = 90
CREATURE_PHOENIX = 91
CREATURE_DEFENDER = 92
CREATURE_STOUT_DEFENDER = 93
CREATURE_AXE_FIGHTER = 94
CREATURE_AXE_THROWER = 95
CREATURE_BEAR_RIDER = 96
CREATURE_BLACKBEAR_RIDER = 97
CREATURE_BROWLER = 98
CREATURE_BERSERKER = 99
CREATURE_RUNE_MAGE = 100
CREATURE_FLAME_MAGE = 101
CREATURE_THANE = 102
CREATURE_WARLORD = 103
CREATURE_FIRE_DRAGON = 104
CREATURE_MAGMA_DRAGON = 105
CREATURE_LANDLORD = 106
CREATURE_LONGBOWMAN = 107
CREATURE_VINDICATOR = 108
CREATURE_BATTLE_GRIFFIN = 109
CREATURE_ZEALOT = 110
CREATURE_CHAMPION = 111
CREATURE_SERAPH = 112
CREATURE_WOLF = 113
CREATURE_SNOW_APE = 114
CREATURE_MANTICORE = 115
CREATURE_MUMMY = 116
CREATURE_GOBLIN = 117
CREATURE_GOBLIN_TRAPPER = 118
CREATURE_CENTAUR = 119
CREATURE_CENTAUR_NOMAD = 120
CREATURE_ORC_WARRIOR = 121
CREATURE_ORC_SLAYER = 122
CREATURE_SHAMAN = 123
CREATURE_SHAMAN_WITCH = 124
CREATURE_ORCCHIEF_BUTCHER = 125
CREATURE_ORCCHIEF_EXECUTIONER = 126
CREATURE_WYVERN = 127
CREATURE_WYVERN_POISONOUS = 128
CREATURE_CYCLOP = 129
CREATURE_CYCLOP_UNTAMED = 130
CREATURE_QUASIT = 131
CREATURE_HORNED_LEAPER = 132
CREATURE_FIREBREATHER_HOUND = 133
CREATURE_SUCCUBUS_SEDUCER = 134
CREATURE_HELLMARE = 135
CREATURE_PIT_SPAWN = 136
CREATURE_ARCH_DEMON = 137
CREATURE_STALKER = 138
CREATURE_BLOOD_WITCH_2 = 139
CREATURE_MINOTAUR_CAPTAIN = 140
CREATURE_BLACK_RIDER = 141
CREATURE_ACIDIC_HYDRA = 142
CREATURE_SHADOW_MISTRESS = 143
CREATURE_RED_DRAGON = 144
CREATURE_DRYAD = 145
CREATURE_BLADE_SINGER = 146
CREATURE_SHARP_SHOOTER = 147
CREATURE_HIGH_DRUID = 148
CREATURE_WHITE_UNICORN = 149
CREATURE_ANGER_TREANT = 150
CREATURE_RAINBOW_DRAGON = 151
CREATURE_SKELETON_WARRIOR = 152
CREATURE_DISEASE_ZOMBIE = 153
CREATURE_POLTERGEIST = 154
CREATURE_NOSFERATU = 155
CREATURE_LICH_MASTER = 156
CREATURE_BANSHEE = 157
CREATURE_HORROR_DRAGON = 158
CREATURE_GREMLIN_SABOTEUR = 159
CREATURE_MARBLE_GARGOYLE = 160
CREATURE_OBSIDIAN_GOLEM = 161
CREATURE_COMBAT_MAGE = 162
CREATURE_DJINN_VIZIER = 163
CREATURE_RAKSHASA_KSHATRI = 164
CREATURE_STORM_LORD = 165
CREATURE_STONE_DEFENDER = 166
CREATURE_HARPOONER = 167
CREATURE_WHITE_BEAR_RIDER = 168
CREATURE_BATTLE_RAGER = 169
CREATURE_FLAME_KEEPER = 170
CREATURE_THUNDER_THANE = 171
CREATURE_LAVA_DRAGON = 172
CREATURE_GOBLIN_DEFILER = 173
CREATURE_CENTAUR_MARADEUR = 174
CREATURE_ORC_WARMONGER = 175
CREATURE_SHAMAN_HAG = 176
CREATURE_ORCCHIEF_CHIEFTAIN = 177
CREATURE_WYVERN_PAOKAI = 178
CREATURE_CYCLOP_BLOODEYED = 179