---@alias HeroSkillType
---|`SKILL_LOGISTICS`
---|`SKILL_WAR_MACHINES`
---|`SKILL_LEARNING`
---|`SKILL_LEADERSHIP`
---|`SKILL_LUCK`
---|`SKILL_OFFENCE`
---|`SKILL_DEFENCE`
---|`SKILL_SORCERY`
---|`SKILL_DESTRUCTIVE_MAGIC`
---|`SKILL_DARK_MAGIC`
---|`SKILL_LIGHT_MAGIC`
---|`SKILL_SUMMONING_MAGIC`
---|`SKILL_TRAINING`
---|`SKILL_GATING`
---|`SKILL_NECROMANCY`
---|`SKILL_AVENGER`
---|`SKILL_ARTIFICIER`
---|`SKILL_INVOCATION`
---|`PERK_PATHFINDING`
---|`PERK_SCOUTING`
---|`PERK_NAVIGATION`
---|`PERK_FIRST_AID`
---|`PERK_BALLISTA`
---|`PERK_CATAPULT`
---|`PERK_INTELLIGENCE`
---|`PERK_SCHOLAR`
---|`PERK_EAGLE_EYE`
---|`PERK_RECRUITMENT`
---|`PERK_ESTATES`
---|`PERK_DIPLOMACY`
---|`PERK_RESISTANCE`
---|`PERK_LUCKY_STRIKE`
---|`PERK_FORTUNATE_ADVENTURER`
---|`PERK_TACTICS`
---|`PERK_ARCHERY`
---|`PERK_FRENZY`
---|`PERK_PROTECTION`
---|`PERK_EVASION`
---|`PERK_TOUGHNESS`
---|`PERK_MYSTICISM`
---|`PERK_WISDOM`
---|`PERK_ARCANE_TRAINING`
---|`PERK_MASTER_OF_ICE`
---|`PERK_MASTER_OF_FIRE`
---|`PERK_MASTER_OF_LIGHTNINGS`
---|`PERK_MASTER_OF_CURSES`
---|`PERK_MASTER_OF_MIND`
---|`PERK_MASTER_OF_SICKNESS`
---|`PERK_MASTER_OF_BLESSING`
---|`PERK_MASTER_OF_ABJURATION`
---|`PERK_MASTER_OF_WRATH`
---|`PERK_MASTER_OF_QUAKES`
---|`PERK_MASTER_OF_CREATURES`
---|`PERK_MASTER_OF_ANIMATION`
---|`PERK_HOLY_CHARGE`
---|`PERK_PRAYER`
---|`PERK_EXPERT_TRAINER`
---|`PERK_CONSUME_CORPSE`
---|`PERK_DEMONIC_FIRE`
---|`PERK_DEMONIC_STRIKE`
---|`PERK_RAISE_ARCHERS`
---|`PERK_NO_REST_FOR_THE_WICKED`
---|`PERK_DEATH_SCREAM`
---|`PERK_MULTISHOT`
---|`PERK_SNIPE_DEAD`
---|`PERK_IMBUE_ARROW`
---|`PERK_MAGIC_BOND`
---|`PERK_MELT_ARTIFACT`
---|`PERK_MAGIC_MIRROR`
---|`PERK_EMPOWERED_SPELLS`
---|`PERK_DARK_RITUAL`
---|`PERK_ELEMENTAL_VISION`
---|`KNIGHT_FEAT_ROAD_HOME`
---|`KNIGHT_FEAT_TRIPLE_BALLISTA`
---|`KNIGHT_FEAT_ENCOURAGE`
---|`KNIGHT_FEAT_RETRIBUTION`
---|`KNIGHT_FEAT_HOLD_GROUND`
---|`KNIGHT_FEAT_GUARDIAN_ANGEL`
---|`KNIGHT_FEAT_STUDENT_AWARD`
---|`KNIGHT_FEAT_GRAIL_VISION`
---|`KNIGHT_FEAT_CASTER_CERTIFICATE`
---|`KNIGHT_FEAT_ANCIENT_SMITHY`
---|`KNIGHT_FEAT_PARIAH`
---|`KNIGHT_FEAT_ELEMENTAL_BALANCE`
---|`KNIGHT_FEAT_ABSOLUTE_CHARGE`
---|`DEMON_FEAT_QUICK_GATING`
---|`DEMON_FEAT_MASTER_OF_SECRETS`
---|`DEMON_FEAT_TRIPLE_CATAPULT`
---|`DEMON_FEAT_GATING_MASTERY`
---|`DEMON_FEAT_CRITICAL_GATING`
---|`DEMON_FEAT_CRITICAL_STRIKE`
---|`DEMON_FEAT_DEMONIC_RETALIATION`
---|`DEMON_FEAT_EXPLODING_CORPSES`
---|`DEMON_FEAT_DEMONIC_FLAME`
---|`DEMON_FEAT_WEAKENING_STRIKE`
---|`DEMON_FEAT_FIRE_PROTECTION`
---|`DEMON_FEAT_FIRE_AFFINITY`
---|`DEMON_FEAT_ABSOLUTE_GATING`
---|`NECROMANCER_FEAT_DEATH_TREAD`
---|`NECROMANCER_FEAT_LAST_AID`
---|`NECROMANCER_FEAT_LORD_OF_UNDEAD`
---|`NECROMANCER_FEAT_HERALD_OF_DEATH`
---|`NECROMANCER_FEAT_DEAD_LUCK`
---|`NECROMANCER_FEAT_CHILLING_STEEL`
---|`NECROMANCER_FEAT_CHILLING_BONES`
---|`NECROMANCER_FEAT_SPELLPROOF_BONES`
---|`NECROMANCER_FEAT_DEADLY_COLD`
---|`NECROMANCER_FEAT_SPIRIT_LINK`
---|`NECROMANCER_FEAT_TWILIGHT`
---|`NECROMANCER_FEAT_HAUNT_MINE`
---|`NECROMANCER_FEAT_ABSOLUTE_FEAR`
---|`RANGER_FEAT_DISGUISE_AND_RECKON`
---|`RANGER_FEAT_IMBUE_BALLISTA`
---|`RANGER_FEAT_CUNNING_OF_THE_WOODS`
---|`RANGER_FEAT_FOREST_GUARD_EMBLEM`
---|`RANGER_FEAT_ELVEN_LUCK`
---|`RANGER_FEAT_FOREST_RAGE`
---|`RANGER_FEAT_LAST_STAND`
---|`RANGER_FEAT_INSIGHTS`
---|`RANGER_FEAT_SUN_FIRE`
---|`RANGER_FEAT_SOIL_BURN`
---|`RANGER_FEAT_STORM_WIND`
---|`RANGER_FEAT_FOG_VEIL`
---|`RANGER_FEAT_ABSOLUTE_LUCK`
---|`WIZARD_FEAT_MARCH_OF_THE_MACHINES`
---|`WIZARD_FEAT_REMOTE_CONTROL`
---|`WIZARD_FEAT_ACADEMY_AWARD`
---|`WIZARD_FEAT_ARTIFICIAL_GLORY`
---|`WIZARD_FEAT_SPOILS_OF_WAR`
---|`WIZARD_FEAT_WILDFIRE`
---|`WIZARD_FEAT_SEAL_OF_PROTECTION`
---|`WIZARD_FEAT_COUNTERSPELL`
---|`WIZARD_FEAT_MAGIC_CUSHION`
---|`WIZARD_FEAT_SUPRESS_DARK`
---|`WIZARD_FEAT_SUPRESS_LIGHT`
---|`WIZARD_FEAT_UNSUMMON`
---|`WIZARD_FEAT_ABSOLUTE_WIZARDY`
---|`WARLOCK_FEAT_TELEPORT_ASSAULT`
---|`WARLOCK_FEAT_SHAKE_GROUND`
---|`WARLOCK_FEAT_DARK_REVELATION`
---|`WARLOCK_FEAT_FAST_AND_FURIOUS`
---|`WARLOCK_FEAT_LUCKY_SPELLS`
---|`WARLOCK_FEAT_POWER_OF_HASTE`
---|`WARLOCK_FEAT_POWER_OF_STONE`
---|`WARLOCK_FEAT_CHAOTIC_SPELLS`
---|`WARLOCK_FEAT_SECRETS_OF_DESTRUCTION`
---|`WARLOCK_FEAT_PAYBACK`
---|`WARLOCK_FEAT_ELITE_CASTERS`
---|`WARLOCK_FEAT_ELEMENTAL_OVERKILL`
---|`WARLOCK_FEAT_ABSOLUTE_CHAINS`
---|`HERO_SKILL_RUNELORE`
---|`HERO_SKILL_REFRESH_RUNE`
---|`HERO_SKILL_STRONG_RUNE`
---|`HERO_SKILL_FINE_RUNE`
---|`HERO_SKILL_QUICKNESS_OF_MIND`
---|`HERO_SKILL_RUNIC_MACHINES`
---|`HERO_SKILL_TAP_RUNES`
---|`HERO_SKILL_RUNIC_ATTUNEMENT`
---|`HERO_SKILL_DWARVEN_LUCK`
---|`HERO_SKILL_OFFENSIVE_FORMATION`
---|`HERO_SKILL_DEFENSIVE_FORMATION`
---|`HERO_SKILL_DISTRACT`
---|`HERO_SKILL_SET_AFIRE`
---|`HERO_SKILL_SHRUG_DARKNESS`
---|`HERO_SKILL_ETERNAL_LIGHT`
---|`HERO_SKILL_RUNIC_ARMOR`
---|`HERO_SKILL_ABSOLUTE_PROTECTION`
---|`HERO_SKILL_SNATCH`
---|`HERO_SKILL_MENTORING`
---|`HERO_SKILL_EMPATHY`
---|`HERO_SKILL_PREPARATION`
---|`HERO_SKILL_DEMONIC_RAGE`
---|`HERO_SKILL_MIGHT_OVER_MAGIC`
---|`HERO_SKILL_MEMORY_OF_OUR_BLOOD`
---|`HERO_SKILL_POWERFULL_BLOW`
---|`HERO_SKILL_ABSOLUTE_RAGE`
---|`HERO_SKILL_PATH_OF_WAR`
---|`HERO_SKILL_BATTLE_ELATION`
---|`HERO_SKILL_LUCK_OF_THE_BARBARIAN`
---|`HERO_SKILL_STUNNING_BLOW`
---|`HERO_SKILL_DEFEND_US_ALL`
---|`HERO_SKILL_GOBLIN_SUPPORT`
---|`HERO_SKILL_BARBARIAN_LEARNING`
---|`HERO_SKILL_POWER_OF_BLOOD`
---|`HERO_SKILL_WARCRY_LEARNING`
---|`HERO_SKILL_BODYBUILDING`
---|`HERO_SKILL_VOICE`
---|`HERO_SKILL_VOICE_TRAINING`
---|`HERO_SKILL_MIGHTY_VOICE`
---|`HERO_SKILL_VOICE_OF_RAGE`
---|`HERO_SKILL_SHATTER_DESTRUCTIVE_MAGIC`
---|`HERO_SKILL_CORRUPT_DESTRUCTIVE`
---|`HERO_SKILL_WEAKEN_DESTRUCTIVE`
---|`HERO_SKILL_DETAIN_DESTRUCTIVE`
---|`HERO_SKILL_SHATTER_DARK_MAGIC`
---|`HERO_SKILL_CORRUPT_DARK`
---|`HERO_SKILL_WEAKEN_DARK`
---|`HERO_SKILL_DETAIN_DARK`
---|`HERO_SKILL_SHATTER_LIGHT_MAGIC`
---|`HERO_SKILL_CORRUPT_LIGHT`
---|`HERO_SKILL_WEAKEN_LIGHT`
---|`HERO_SKILL_DETAIN_LIGHT`
---|`HERO_SKILL_SHATTER_SUMMONING_MAGIC`
---|`HERO_SKILL_CORRUPT_SUMMONING`
---|`HERO_SKILL_WEAKEN_SUMMONING`
---|`HERO_SKILL_DETAIN_SUMMONING`
---|`HERO_SKILL_DEATH_TO_NONEXISTENT`
---|`HERO_SKILL_BARBARIAN_ANCIENT_SMITHY`
---|`HERO_SKILL_BARBARIAN_WEAKENING_STRIKE`
---|`HERO_SKILL_BARBARIAN_SOIL_BURN`
---|`HERO_SKILL_BARBARIAN_FOG_VEIL`
---|`HERO_SKILL_BARBARIAN_INTELLIGENCE`
---|`HERO_SKILL_BARBARIAN_MYSTICISM`
---|`HERO_SKILL_BARBARIAN_ELITE_CASTERS`
---|`HERO_SKILL_BARBARIAN_STORM_WIND`
SKILL_LOGISTICS = 1
SKILL_WAR_MACHINES = 2
SKILL_LEARNING = 3
SKILL_LEADERSHIP = 4
SKILL_LUCK = 5
SKILL_OFFENCE = 6
SKILL_DEFENCE = 7
SKILL_SORCERY = 8
SKILL_DESTRUCTIVE_MAGIC = 9
SKILL_DARK_MAGIC = 10
SKILL_LIGHT_MAGIC = 11
SKILL_SUMMONING_MAGIC = 12
SKILL_TRAINING   = 13
SKILL_GATING     = 14
SKILL_NECROMANCY = 15
SKILL_AVENGER = 16
SKILL_ARTIFICIER = 17
SKILL_INVOCATION = 18
PERK_PATHFINDING = 19
PERK_SCOUTING = 20
PERK_NAVIGATION = 21
PERK_FIRST_AID = 22
PERK_BALLISTA = 23
PERK_CATAPULT = 24
PERK_INTELLIGENCE = 25
PERK_SCHOLAR = 26
PERK_EAGLE_EYE = 27
PERK_RECRUITMENT = 28
PERK_ESTATES = 29
PERK_DIPLOMACY = 30
PERK_RESISTANCE = 31
PERK_LUCKY_STRIKE = 32
PERK_FORTUNATE_ADVENTURER = 33
PERK_TACTICS = 34
PERK_ARCHERY = 35
PERK_FRENZY = 36
PERK_PROTECTION = 37
PERK_EVASION = 38
PERK_TOUGHNESS = 39
PERK_MYSTICISM = 40
PERK_WISDOM = 41
PERK_ARCANE_TRAINING = 42
PERK_MASTER_OF_ICE = 43
PERK_MASTER_OF_FIRE = 44
PERK_MASTER_OF_LIGHTNINGS = 45
PERK_MASTER_OF_CURSES = 46
PERK_MASTER_OF_MIND = 47
PERK_MASTER_OF_SICKNESS = 48
PERK_MASTER_OF_BLESSING = 49
PERK_MASTER_OF_ABJURATION = 50
PERK_MASTER_OF_WRATH = 51
PERK_MASTER_OF_QUAKES = 52
PERK_MASTER_OF_CREATURES = 53
PERK_MASTER_OF_ANIMATION = 54
PERK_HOLY_CHARGE = 55
PERK_PRAYER = 56
PERK_EXPERT_TRAINER = 57
PERK_CONSUME_CORPSE = 58
PERK_DEMONIC_FIRE = 59
PERK_DEMONIC_STRIKE = 60
PERK_RAISE_ARCHERS          = 61
PERK_NO_REST_FOR_THE_WICKED = 62
PERK_DEATH_SCREAM           = 63
PERK_MULTISHOT = 64
PERK_SNIPE_DEAD = 65
PERK_IMBUE_ARROW = 66
PERK_MAGIC_BOND = 67
PERK_MELT_ARTIFACT = 68
PERK_MAGIC_MIRROR = 69
PERK_EMPOWERED_SPELLS = 70
PERK_DARK_RITUAL = 71
PERK_ELEMENTAL_VISION = 72
KNIGHT_FEAT_ROAD_HOME = 73
KNIGHT_FEAT_TRIPLE_BALLISTA = 74
KNIGHT_FEAT_ENCOURAGE = 75
KNIGHT_FEAT_RETRIBUTION = 76
KNIGHT_FEAT_HOLD_GROUND = 77
KNIGHT_FEAT_GUARDIAN_ANGEL = 78
KNIGHT_FEAT_STUDENT_AWARD = 79
KNIGHT_FEAT_GRAIL_VISION = 80
KNIGHT_FEAT_CASTER_CERTIFICATE = 81
KNIGHT_FEAT_ANCIENT_SMITHY = 82
KNIGHT_FEAT_PARIAH = 83
KNIGHT_FEAT_ELEMENTAL_BALANCE = 84
KNIGHT_FEAT_ABSOLUTE_CHARGE = 85
DEMON_FEAT_QUICK_GATING = 86
DEMON_FEAT_MASTER_OF_SECRETS = 87
DEMON_FEAT_TRIPLE_CATAPULT = 88
DEMON_FEAT_GATING_MASTERY = 89
DEMON_FEAT_CRITICAL_GATING = 90
DEMON_FEAT_CRITICAL_STRIKE = 91
DEMON_FEAT_DEMONIC_RETALIATION = 92
DEMON_FEAT_EXPLODING_CORPSES = 93
DEMON_FEAT_DEMONIC_FLAME = 94
DEMON_FEAT_WEAKENING_STRIKE = 95
DEMON_FEAT_FIRE_PROTECTION = 96
DEMON_FEAT_FIRE_AFFINITY = 97
DEMON_FEAT_ABSOLUTE_GATING = 98
NECROMANCER_FEAT_DEATH_TREAD = 99
NECROMANCER_FEAT_LAST_AID = 100
NECROMANCER_FEAT_LORD_OF_UNDEAD = 101
NECROMANCER_FEAT_HERALD_OF_DEATH = 102
NECROMANCER_FEAT_DEAD_LUCK = 103
NECROMANCER_FEAT_CHILLING_STEEL = 104
NECROMANCER_FEAT_CHILLING_BONES = 105
NECROMANCER_FEAT_SPELLPROOF_BONES = 106
NECROMANCER_FEAT_DEADLY_COLD = 107
NECROMANCER_FEAT_SPIRIT_LINK = 108
NECROMANCER_FEAT_TWILIGHT = 109
NECROMANCER_FEAT_HAUNT_MINE = 110
NECROMANCER_FEAT_ABSOLUTE_FEAR = 111
RANGER_FEAT_DISGUISE_AND_RECKON = 112
RANGER_FEAT_IMBUE_BALLISTA = 113
RANGER_FEAT_CUNNING_OF_THE_WOODS = 114
RANGER_FEAT_FOREST_GUARD_EMBLEM = 115
RANGER_FEAT_ELVEN_LUCK = 116
RANGER_FEAT_FOREST_RAGE = 117
RANGER_FEAT_LAST_STAND = 118
RANGER_FEAT_INSIGHTS = 119
RANGER_FEAT_SUN_FIRE = 120
RANGER_FEAT_SOIL_BURN = 121
RANGER_FEAT_STORM_WIND = 122
RANGER_FEAT_FOG_VEIL = 123
RANGER_FEAT_ABSOLUTE_LUCK = 124
WIZARD_FEAT_MARCH_OF_THE_MACHINES = 125
WIZARD_FEAT_REMOTE_CONTROL = 126
WIZARD_FEAT_ACADEMY_AWARD = 127
WIZARD_FEAT_ARTIFICIAL_GLORY = 128
WIZARD_FEAT_SPOILS_OF_WAR = 129
WIZARD_FEAT_WILDFIRE = 130
WIZARD_FEAT_SEAL_OF_PROTECTION = 131
WIZARD_FEAT_COUNTERSPELL = 132
WIZARD_FEAT_MAGIC_CUSHION = 133
WIZARD_FEAT_SUPRESS_DARK  = 134
WIZARD_FEAT_SUPRESS_LIGHT  = 135
WIZARD_FEAT_UNSUMMON  = 136
WIZARD_FEAT_ABSOLUTE_WIZARDY = 137
WARLOCK_FEAT_TELEPORT_ASSAULT = 138
WARLOCK_FEAT_SHAKE_GROUND = 139
WARLOCK_FEAT_DARK_REVELATION = 140
WARLOCK_FEAT_FAST_AND_FURIOUS = 141
WARLOCK_FEAT_LUCKY_SPELLS = 142
WARLOCK_FEAT_POWER_OF_HASTE = 143
WARLOCK_FEAT_POWER_OF_STONE = 144
WARLOCK_FEAT_CHAOTIC_SPELLS = 145
WARLOCK_FEAT_SECRETS_OF_DESTRUCTION = 146
WARLOCK_FEAT_PAYBACK = 147
WARLOCK_FEAT_ELITE_CASTERS = 148
WARLOCK_FEAT_ELEMENTAL_OVERKILL	= 149
WARLOCK_FEAT_ABSOLUTE_CHAINS = 150
HERO_SKILL_RUNELORE = 151
HERO_SKILL_REFRESH_RUNE = 152
HERO_SKILL_STRONG_RUNE = 153
HERO_SKILL_FINE_RUNE = 154
HERO_SKILL_QUICKNESS_OF_MIND = 155
HERO_SKILL_RUNIC_MACHINES = 156
HERO_SKILL_TAP_RUNES = 157
HERO_SKILL_RUNIC_ATTUNEMENT = 158
HERO_SKILL_DWARVEN_LUCK = 159
HERO_SKILL_OFFENSIVE_FORMATION = 160
HERO_SKILL_DEFENSIVE_FORMATION = 161
HERO_SKILL_DISTRACT = 162
HERO_SKILL_SET_AFIRE = 163
HERO_SKILL_SHRUG_DARKNESS = 164
HERO_SKILL_ETERNAL_LIGHT = 165
HERO_SKILL_RUNIC_ARMOR = 166
HERO_SKILL_ABSOLUTE_PROTECTION = 167
HERO_SKILL_SNATCH = 168
HERO_SKILL_MENTORING = 169
HERO_SKILL_EMPATHY = 170
HERO_SKILL_PREPARATION = 171
HERO_SKILL_DEMONIC_RAGE = 172
HERO_SKILL_MIGHT_OVER_MAGIC = 173
HERO_SKILL_MEMORY_OF_OUR_BLOOD = 174
HERO_SKILL_POWERFULL_BLOW = 175
HERO_SKILL_ABSOLUTE_RAGE = 176
HERO_SKILL_PATH_OF_WAR = 177
HERO_SKILL_BATTLE_ELATION = 178
HERO_SKILL_LUCK_OF_THE_BARBARIAN = 179
HERO_SKILL_STUNNING_BLOW = 180
HERO_SKILL_DEFEND_US_ALL = 181
HERO_SKILL_GOBLIN_SUPPORT = 182
HERO_SKILL_BARBARIAN_LEARNING = 183
HERO_SKILL_POWER_OF_BLOOD = 184
HERO_SKILL_WARCRY_LEARNING = 185
HERO_SKILL_BODYBUILDING = 186
HERO_SKILL_VOICE = 187
HERO_SKILL_VOICE_TRAINING = 188
HERO_SKILL_MIGHTY_VOICE = 189
HERO_SKILL_VOICE_OF_RAGE = 190
HERO_SKILL_SHATTER_DESTRUCTIVE_MAGIC = 191
HERO_SKILL_CORRUPT_DESTRUCTIVE = 192
HERO_SKILL_WEAKEN_DESTRUCTIVE = 193
HERO_SKILL_DETAIN_DESTRUCTIVE = 194
HERO_SKILL_SHATTER_DARK_MAGIC = 195
HERO_SKILL_CORRUPT_DARK = 196
HERO_SKILL_WEAKEN_DARK = 197
HERO_SKILL_DETAIN_DARK = 198
HERO_SKILL_SHATTER_LIGHT_MAGIC = 199
HERO_SKILL_CORRUPT_LIGHT = 200
HERO_SKILL_WEAKEN_LIGHT = 201
HERO_SKILL_DETAIN_LIGHT = 202
HERO_SKILL_SHATTER_SUMMONING_MAGIC = 203
HERO_SKILL_CORRUPT_SUMMONING = 204
HERO_SKILL_WEAKEN_SUMMONING = 205
HERO_SKILL_DETAIN_SUMMONING = 206
HERO_SKILL_DEATH_TO_NONEXISTENT = 207
HERO_SKILL_BARBARIAN_ANCIENT_SMITHY = 208
HERO_SKILL_BARBARIAN_WEAKENING_STRIKE = 209
HERO_SKILL_BARBARIAN_SOIL_BURN = 210
HERO_SKILL_BARBARIAN_FOG_VEIL = 211
HERO_SKILL_BARBARIAN_INTELLIGENCE = 212
HERO_SKILL_BARBARIAN_MYSTICISM = 213
HERO_SKILL_BARBARIAN_ELITE_CASTERS = 214
HERO_SKILL_BARBARIAN_STORM_WIND = 215