---@alias TownBuildingType
---|`TOWN_BUILDING_TOWN_HALL`
---|`TOWN_BUILDING_FORT`
---|`TOWN_BUILDING_MARKETPLACE`
---|`TOWN_BUILDING_SHIPYARD`
---|`TOWN_BUILDING_TAVERN`
---|`TOWN_BUILDING_BLACKSMITH`
---|`TOWN_BUILDING_MAGIC_GUILD`
---|`TOWN_BUILDING_DWELLING_1`
---|`TOWN_BUILDING_DWELLING_2`
---|`TOWN_BUILDING_DWELLING_3`
---|`TOWN_BUILDING_DWELLING_4`
---|`TOWN_BUILDING_DWELLING_5`
---|`TOWN_BUILDING_DWELLING_6`
---|`TOWN_BUILDING_DWELLING_7`
---|`TOWN_BUILDING_GRAIL`
---|`TOWN_BUILDING_WONDER`
---|`TOWN_BUILDING_SPECIAL_0`
---|`TOWN_BUILDING_SPECIAL_1`
---|`TOWN_BUILDING_SPECIAL_2`
---|`TOWN_BUILDING_SPECIAL_3`
---|`TOWN_BUILDING_SPECIAL_4`
---|`TOWN_BUILDING_SPECIAL_5`
---|`TOWN_BUILDING_SPECIAL_6`
---|`TOWN_BUILDING_SPECIAL_7`
---|`TOWN_BUILDING_SPECIAL_8`
---|`TOWN_BUILDING_SPECIAL_9`
---|`TOWN_BUILDING_HAVEN_TRAINING_GROUNDS`
---|`TOWN_BUILDING_HAVEN_MONUMENT_TO_FALLEN_HEROES`
---|`TOWN_BUILDING_HAVEN_HOSPITAL`
---|`TOWN_BUILDING_HAVEN_STABLE`
---|`TOWN_BUILDING_HAVEN_FARMS`
---|`TOWN_BUILDING_INFERNO_INFERNAL_LOOM`
---|`TOWN_BUILDING_INFERNO_ORDER_OF_FIRE`
---|`TOWN_BUILDING_INFERNO_HALLS_OF_HORROR`
---|`TOWN_BUILDING_INFERNO_SACRIFICIAL_PIT`
---|`TOWN_BUILDING_DUNGEON_ALTAR_OF_ELEMENTS`
---|`TOWN_BUILDING_DUNGEON_RITUAL_PIT`
---|`TOWN_BUILDING_DUNGEON_TRADE_GUILD`
---|`TOWN_BUILDING_DUNGEON_TREASURE_DIG_SITE`
---|`TOWN_BUILDING_DUNGEON_HALL_OF_INTRIGUE`
---|`TOWN_BUILDING_ACADEMY_LIBRARY`
---|`TOWN_BUILDING_ACADEMY_ARCANE_FORGE`
---|`TOWN_BUILDING_ACADEMY_ARTIFACT_MERCHANT`
---|`TOWN_BUILDING_ACADEMY_TREASURE_CAVE`
---|`TOWN_BUILDING_ACADEMY_ELEMENTAL_ENCLAVE`
---|`TOWN_BUILDING_PRESERVE_AVENGERS_BROTHERHOOD`
---|`TOWN_BUILDING_PRESERVE_MYSTIC_POND`
---|`TOWN_BUILDING_PRESERVE_SPARKLING_FONTAINS`
---|`TOWN_BUILDING_PRESERVE_BLOOMING_GROVE`
---|`TOWN_BUILDING_PRESERVE_TREANT_SAMPLING`
---|`TOWN_BUILDING_NECROMANCY_AMPLIFIER`
---|`TOWN_BUILDING_NECROMANCY_UNHOLY_TEMPLE`
---|`TOWN_BUILDING_NECROMANCY_UNEARHED_GRAVES`
---|`TOWN_BUILDING_NECROMANCY_DRAGON_TOMBSTONE`
---|`TOWN_BUILDING_NECROMANCY_SHROUD_OF_DARKNESS`
---|`TOWN_BUILDING_FORTRESS_RUNIC_SHRINE`
---|`TOWN_BUILDING_FORTRESS_ARENA`
---|`TOWN_BUILDING_FORTRESS_GUARDPOST`
---|`TOWN_BUILDING_FORTRESS_RUNIC_STONEWORKS`
---|`TOWN_BUILDING_FORTRESS_RUNIC_ACADEMY`
---|`TOWN_BUILDING_STRONGHOLD_HALL_OF_TRIAL`
---|`TOWN_BUILDING_STRONGHOLD_GARBAGE_PILE`
---|`TOWN_BUILDING_STRONGHOLD_TRAVELLERS_SHELTER`
---|`TOWN_BUILDING_STRONGHOLD_PILE_OF_OUR_FOES`
---|`TOWN_BUILDING_STRONGHOLD_SLAVE_MARKET`
TOWN_BUILDING_TOWN_HALL = 0
TOWN_BUILDING_FORT = 1
TOWN_BUILDING_MARKETPLACE = 2	
TOWN_BUILDING_SHIPYARD = 3
TOWN_BUILDING_TAVERN = 4
TOWN_BUILDING_BLACKSMITH = 5
TOWN_BUILDING_MAGIC_GUILD = 6
TOWN_BUILDING_DWELLING_1 = 7
TOWN_BUILDING_DWELLING_2 = 8
TOWN_BUILDING_DWELLING_3 = 9
TOWN_BUILDING_DWELLING_4 = 10
TOWN_BUILDING_DWELLING_5 = 11
TOWN_BUILDING_DWELLING_6 = 12
TOWN_BUILDING_DWELLING_7 = 13
TOWN_BUILDING_GRAIL = 14
TOWN_BUILDING_WONDER = 15
TOWN_BUILDING_SPECIAL_0 = 16
TOWN_BUILDING_SPECIAL_1 = 17
TOWN_BUILDING_SPECIAL_2 = 18
TOWN_BUILDING_SPECIAL_3 = 19
TOWN_BUILDING_SPECIAL_4 = 20
TOWN_BUILDING_SPECIAL_5 = 21
TOWN_BUILDING_SPECIAL_6 = 22
TOWN_BUILDING_SPECIAL_7 = 23
TOWN_BUILDING_SPECIAL_8 = 24
TOWN_BUILDING_SPECIAL_9 = 25
TOWN_BUILDING_HAVEN_TRAINING_GROUNDS 			= TOWN_BUILDING_SPECIAL_1
TOWN_BUILDING_HAVEN_MONUMENT_TO_FALLEN_HEROES 	= TOWN_BUILDING_SPECIAL_2
TOWN_BUILDING_HAVEN_HOSPITAL 					= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_HAVEN_STABLE 						= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_HAVEN_FARMS 						= TOWN_BUILDING_SPECIAL_5
TOWN_BUILDING_INFERNO_INFERNAL_LOOM 			= TOWN_BUILDING_SPECIAL_1
TOWN_BUILDING_INFERNO_ORDER_OF_FIRE 			= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_INFERNO_HALLS_OF_HORROR 			= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_INFERNO_SACRIFICIAL_PIT 			= TOWN_BUILDING_SPECIAL_5
TOWN_BUILDING_DUNGEON_ALTAR_OF_ELEMENTS 		= TOWN_BUILDING_SPECIAL_1
TOWN_BUILDING_DUNGEON_RITUAL_PIT 				= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_DUNGEON_TRADE_GUILD				= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_DUNGEON_TREASURE_DIG_SITE 		= TOWN_BUILDING_SPECIAL_5
TOWN_BUILDING_DUNGEON_HALL_OF_INTRIGUE 			= TOWN_BUILDING_SPECIAL_6
TOWN_BUILDING_ACADEMY_LIBRARY 					= TOWN_BUILDING_SPECIAL_1
TOWN_BUILDING_ACADEMY_ARCANE_FORGE 				= TOWN_BUILDING_SPECIAL_2
TOWN_BUILDING_ACADEMY_ARTIFACT_MERCHANT			= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_ACADEMY_TREASURE_CAVE 			= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_ACADEMY_ELEMENTAL_ENCLAVE 		= TOWN_BUILDING_SPECIAL_5
TOWN_BUILDING_PRESERVE_AVENGERS_BROTHERHOOD		= TOWN_BUILDING_SPECIAL_0
TOWN_BUILDING_PRESERVE_MYSTIC_POND 				= TOWN_BUILDING_SPECIAL_2
TOWN_BUILDING_PRESERVE_SPARKLING_FONTAINS 		= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_PRESERVE_BLOOMING_GROVE 			= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_PRESERVE_TREANT_SAMPLING 			= TOWN_BUILDING_SPECIAL_5
TOWN_BUILDING_NECROMANCY_AMPLIFIER 				= TOWN_BUILDING_SPECIAL_1
TOWN_BUILDING_NECROMANCY_UNHOLY_TEMPLE 			= TOWN_BUILDING_SPECIAL_2
TOWN_BUILDING_NECROMANCY_UNEARHED_GRAVES 		= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_NECROMANCY_DRAGON_TOMBSTONE 		= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_NECROMANCY_SHROUD_OF_DARKNESS 	= TOWN_BUILDING_SPECIAL_5
TOWN_BUILDING_FORTRESS_RUNIC_SHRINE 		= TOWN_BUILDING_SPECIAL_1;
TOWN_BUILDING_FORTRESS_ARENA 			= TOWN_BUILDING_SPECIAL_2;
TOWN_BUILDING_FORTRESS_GUARDPOST 		= TOWN_BUILDING_SPECIAL_3;
TOWN_BUILDING_FORTRESS_RUNIC_STONEWORKS 	= TOWN_BUILDING_SPECIAL_4;
TOWN_BUILDING_FORTRESS_RUNIC_ACADEMY 		= TOWN_BUILDING_SPECIAL_5;
TOWN_BUILDING_STRONGHOLD_HALL_OF_TRIAL			= TOWN_BUILDING_SPECIAL_1
TOWN_BUILDING_STRONGHOLD_GARBAGE_PILE			= TOWN_BUILDING_SPECIAL_2
TOWN_BUILDING_STRONGHOLD_TRAVELLERS_SHELTER	= TOWN_BUILDING_SPECIAL_3
TOWN_BUILDING_STRONGHOLD_PILE_OF_OUR_FOES		= TOWN_BUILDING_SPECIAL_4
TOWN_BUILDING_STRONGHOLD_SLAVE_MARKET			= TOWN_BUILDING_SPECIAL_5