---@alias WeekType
---|`WEEK_OF_NOTHING`
---|`WEEK_OF_TOAD`
---|`WEEK_OF_SALAMANDER`
---|`WEEK_OF_BEETLE`
---|`WEEK_OF_WYVERN`
---|`WEEK_OF_DRAGONFLY`
---|`WEEK_OF_FOX`
---|`WEEK_OF_SHAMAN`
---|`WEEK_OF_RABBIT`
---|`WEEK_OF_SQUIRREL`
---|`WEEK_OF_CATERPILLAR`
---|`WEEK_OF_HAMSTER`
---|`WEEK_OF_PIGEON`
---|`WEEK_OF_RAGE`
---|`WEEK_OF_EAGLE`
---|`WEEK_OF_BEE`
---|`WEEK_OF_WASP`
---|`WEEK_OF_SWAN`
---|`WEEK_OF_BUTTERFLY`
---|`WEEK_OF_THANE`
---|`WEEK_OF_ANTILOPE`
---|`WEEK_OF_ORC`
---|`WEEK_OF_RAVEN`
---|`WEEK_OF_BADGER`
---|`WEEK_OF_FLAMINGO`
---|`WEEK_OF_TORTOISE`
---|`WEEK_OF_LYNX`
---|`WEEK_OF_PENGUIN`
---|`WEEK_OF_FALCON`
---|`WEEK_OF_HEDGEHOG`
---|`WEEK_OF_SPARROW`
---|`WEEK_OF_SWALLOW`
---|`WEEK_OF_LION`
---|`WEEK_OF_SPEARS`
---|`WEEK_OF_BEAR`
---|`WEEK_OF_CHIEFTAIN`
---|`WEEK_OF_CENTAUR`
---|`WEEK_OF_GOBLIN`
---|`WEEK_OF_DEER`
---|`WEEK_OF_OWL`
---|`WEEK_OF_DEFENDER`
---|`WEEK_OF_WYRM`
---|`WEEK_OF_TIGER`
---|`WEEK_OF_PLAGUE`
---|`WEEK_OF_DISEASE`
---|`WEEK_OF_FEVER`
---|`WEEK_OF_FLAME`
---|`WEEK_OF_WINDS`
---|`WEEK_OF_FOLLY`
---|`WEEK_OF_HONOR`
---|`WEEK_OF_DIPLOMACY`
---|`WEEK_OF_FORGERY`
---|`WEEK_OF_TRADE`
---|`WEEK_OF_MEDITATION`
---|`WEEK_OF_LIFE`
---|`WEEK_OF_CONJUNCTION`
---|`WEEK_OF_JEWELS`
---|`WEEK_OF_ALCHEMY`
---|`WEEK_OF_GOLD`
---|`WEEK_OF_FESTIVALS`
---|`WEEK_OF_HARVEST`
---|`WEEK_OF_IDLENESS`
---|`WEEK_OF_MAGIC`
---|`WEEK_OF_FEEBLENESS`
---|`WEEK_OF_SORROW`
---|`WEEK_OF_CHAOS`
---|`WEEK_OF_CALM`
---|`WEEK_OF_HOPE`
---|`WEEK_OF_WATER`
---|`WEEK_OF_FIRE`
---|`WEEK_OF_EARTH`
---|`WEEK_OF_AIR`
---|`WEEK_OF_FIRENICE`
---|`WEEK_OF_MIGHT`
---|`WEEK_OF_BALANCE`
---|`WEEK_OF_MIGHTNMAGIC`
---|`WEEK_OF_INFIRMITY`
---|`WEEK_OF_LIGHT`
---|`WEEK_OF_EVOCATION`
---|`WEEK_OF_ABJURATION`
---|`WEEK_OF_ALTERATION`
---|`WEEK_OF_CONJURATION`
---|`WEEK_OF_ETHER`
---|`WEEK_OF_TOUGHNESS`
---|`WEEK_OF_PEASANT`
---|`WEEK_OF_ARCHER`
---|`WEEK_OF_FOOTMAN`
---|`WEEK_OF_GRIFFIN`
---|`WEEK_OF_PRIEST`
---|`WEEK_OF_CAVALIER`
---|`WEEK_OF_ANGEL`
---|`WEEK_OF_GREMLIN`
---|`WEEK_OF_GARGOYLE`
---|`WEEK_OF_GOLEM`
---|`WEEK_OF_MAGI`
---|`WEEK_OF_GENIE`
---|`WEEK_OF_RAKSHASA`
---|`WEEK_OF_GIANT`
---|`WEEK_OF_PIXIE`
---|`WEEK_OF_WARDANCER`
---|`WEEK_OF_WOODELF`
---|`WEEK_OF_DRUID`
---|`WEEK_OF_UNICORN`
---|`WEEK_OF_TREANT`
---|`WEEK_OF_GREENDRAGON`
---|`WEEK_OF_IMP`
---|`WEEK_OF_DEMON`
---|`WEEK_OF_HELLHOUND`
---|`WEEK_OF_SUCCUBUS`
---|`WEEK_OF_NIGHTMARE`
---|`WEEK_OF_BALOR`
---|`WEEK_OF_DEVIL`
---|`WEEK_OF_ASSASSIN`
---|`WEEK_OF_WITCH`
---|`WEEK_OF_MINOTAUR`
---|`WEEK_OF_RIDER`
---|`WEEK_OF_HYDRA`
---|`WEEK_OF_MATRON`
---|`WEEK_OF_DRAGON`
---|`WEEK_OF_SKELETON`
---|`WEEK_OF_WALKINGDEAD`
---|`WEEK_OF_WIGHT`
---|`WEEK_OF_VAMPIRE`
---|`WEEK_OF_LICH`
---|`WEEK_OF_GHOST`
---|`WEEK_OF_BONEDRAGON`
WEEK_OF_NOTHING = 0
WEEK_OF_TOAD = 1
WEEK_OF_SALAMANDER = 2
WEEK_OF_BEETLE = 3
WEEK_OF_WYVERN = 4
WEEK_OF_DRAGONFLY = 5
WEEK_OF_FOX = 6
WEEK_OF_SHAMAN = 7
WEEK_OF_RABBIT = 8
WEEK_OF_SQUIRREL = 9
WEEK_OF_CATERPILLAR = 10
WEEK_OF_HAMSTER = 11
WEEK_OF_PIGEON = 12
WEEK_OF_RAGE = 13
WEEK_OF_EAGLE = 14
WEEK_OF_BEE = 15
WEEK_OF_WASP = 16
WEEK_OF_SWAN = 17
WEEK_OF_BUTTERFLY = 18
WEEK_OF_THANE = 19
WEEK_OF_ANTILOPE = 20
WEEK_OF_ORC = 21
WEEK_OF_RAVEN = 22
WEEK_OF_BADGER = 23
WEEK_OF_FLAMINGO = 24
WEEK_OF_TORTOISE = 25
WEEK_OF_LYNX = 26
WEEK_OF_PENGUIN = 27
WEEK_OF_FALCON = 28
WEEK_OF_HEDGEHOG = 29
WEEK_OF_SPARROW = 30
WEEK_OF_SWALLOW = 31
WEEK_OF_LION = 32
WEEK_OF_SPEARS = 33
WEEK_OF_BEAR = 34
WEEK_OF_CHIEFTAIN = 35
WEEK_OF_CENTAUR = 36
WEEK_OF_GOBLIN = 37
WEEK_OF_DEER = 38
WEEK_OF_OWL = 39
WEEK_OF_DEFENDER = 40
WEEK_OF_WYRM = 41
WEEK_OF_TIGER = 42
WEEK_OF_PLAGUE = 43
WEEK_OF_DISEASE = 44
WEEK_OF_FEVER = 45
WEEK_OF_FLAME = 46
WEEK_OF_WINDS = 47
WEEK_OF_FOLLY = 48
WEEK_OF_HONOR = 49
WEEK_OF_DIPLOMACY = 50
WEEK_OF_FORGERY = 51
WEEK_OF_TRADE = 52
WEEK_OF_MEDITATION = 53
WEEK_OF_LIFE = 54
WEEK_OF_CONJUNCTION = 55
WEEK_OF_JEWELS = 56
WEEK_OF_ALCHEMY = 57
WEEK_OF_GOLD = 58
WEEK_OF_FESTIVALS = 59
WEEK_OF_HARVEST = 60
WEEK_OF_IDLENESS = 61
WEEK_OF_MAGIC = 62
WEEK_OF_FEEBLENESS = 63
WEEK_OF_SORROW = 64
WEEK_OF_CHAOS = 65
WEEK_OF_CALM = 66
WEEK_OF_HOPE = 67
WEEK_OF_WATER = 68
WEEK_OF_FIRE = 69
WEEK_OF_EARTH = 70
WEEK_OF_AIR = 71
WEEK_OF_FIRENICE = 72
WEEK_OF_MIGHT = 73
WEEK_OF_BALANCE = 74
WEEK_OF_MIGHTNMAGIC = 75
WEEK_OF_INFIRMITY = 76
WEEK_OF_LIGHT = 77
WEEK_OF_EVOCATION = 78
WEEK_OF_ABJURATION = 79
WEEK_OF_ALTERATION = 80
WEEK_OF_CONJURATION = 81
WEEK_OF_ETHER = 82
WEEK_OF_TOUGHNESS = 83
WEEK_OF_PEASANT = 84
WEEK_OF_ARCHER = 85
WEEK_OF_FOOTMAN = 86
WEEK_OF_GRIFFIN = 87
WEEK_OF_PRIEST = 88
WEEK_OF_CAVALIER = 89
WEEK_OF_ANGEL = 90
WEEK_OF_GREMLIN = 91
WEEK_OF_GARGOYLE = 92
WEEK_OF_GOLEM = 93
WEEK_OF_MAGI = 94
WEEK_OF_GENIE = 95
WEEK_OF_RAKSHASA = 96
WEEK_OF_GIANT = 97
WEEK_OF_PIXIE = 98
WEEK_OF_WARDANCER = 99
WEEK_OF_WOODELF = 100
WEEK_OF_DRUID = 101
WEEK_OF_UNICORN = 102
WEEK_OF_TREANT = 103
WEEK_OF_GREENDRAGON = 104
WEEK_OF_IMP = 105
WEEK_OF_DEMON = 106
WEEK_OF_HELLHOUND = 107
WEEK_OF_SUCCUBUS = 108
WEEK_OF_NIGHTMARE = 109
WEEK_OF_BALOR = 110
WEEK_OF_DEVIL = 111
WEEK_OF_ASSASSIN = 112
WEEK_OF_WITCH = 113
WEEK_OF_MINOTAUR = 114
WEEK_OF_RIDER = 115
WEEK_OF_HYDRA = 116
WEEK_OF_MATRON = 117
WEEK_OF_DRAGON = 118
WEEK_OF_SKELETON = 119
WEEK_OF_WALKINGDEAD = 120
WEEK_OF_WIGHT = 121
WEEK_OF_VAMPIRE = 122
WEEK_OF_LICH = 123
WEEK_OF_GHOST = 124
WEEK_OF_BONEDRAGON = 125