consoleCmd('console_size 10000')
doFile('/scripts/source/3rdparty/lualib.lua')
doFile("/scripts/source/common/global/consts.lua")
doFile("/scripts/source/common/random.lua")
sleep()
doFile("/scripts/source/entity/creature/abils.lua")
doFile("/scripts/source/entity/creature/consts.lua")
doFile("/scripts/source/entity/artifact/consts.lua")
doFile("/scripts/source/entity/hero/consts.lua")
doFile("/scripts/source/entity/spell/consts.lua")
sleep()
while not HERO_SPEC_NONE and TOWN_NO_TYPE do
	sleep()
end
doFile('/scripts/generated_info.lua')
sleep()
doFile("/scripts/source/entity/load.lua")
sleep()
doFile("/scripts/source/common/combat/override.lua")
doFile("/scripts/source/common/combat/misc.lua")