---@alias CombatSide
---|`ATTACKER`
---|`DEFENDER`
ATTACKER = 0
DEFENDER = 1

---@alias CombatControlMode
---|`MODE_NORMAL`
---|`MODE_MANUAL`
---|`MODE_AUTO`
MODE_NORMAL = 0
MODE_MANUAL = 1
MODE_AUTO = 2

---@alias CombatUnitType
---|`HERO`
---|`CREATURE`
---|`WAR_MACHINE`
---|`BUILDING`
---|`SPELL_SPAWN`
HERO = 0
CREATURE = 1
WAR_MACHINE = 2
BUILDING = 3
SPELL_SPAWN = 4

---@alias CombatBuildingType
---|`BUILDING_WALL`
---|`BUILDING_GATE`
---|`BUILDING_LEFT_TOWER`
---|`BUILDING_BIG_TOWER`
---|`BUILDING_MOAT`
---|`BUILDING_RIGHT_TOWER`
---|`BUILDING_MAGIC_WALL`
BUILDING_WALL = 1
BUILDING_GATE = 2
BUILDING_LEFT_TOWER = 3
BUILDING_BIG_TOWER = 4
BUILDING_MOAT = 5
BUILDING_RIGHT_TOWER = 6
BUILDING_MAGIC_WALL = 7

---@alias CombatHostType
---|`HUMAN`
---|`COMPUTER`
HUMAN = 0
COMPUTER = 1