NO_ABILS = 0
HAS_BY_DEFAULT = 1
MCCS_CHANGED = 2

---@alias CreatureFractionType
---|`CREATURE_FRAC_KIND`
---|`CREATURE_FRAC_EVIL`
---|`CREATURE_FRAC_NEUTRAL`
CREATURE_FRAC_KIND    = 1
CREATURE_FRAC_EVIL    = 2
CREATURE_FRAC_NEUTRAL = 3

---@alias CreatureMagicElementType
---|`ELEMENT_NONE`
---|`ELEMENT_FIRE`
---|`ELEMENT_WATER`
---|`ELEMENT_AIR`
---|`ELEMENT_EARTH`
ELEMENT_NONE = 0
ELEMENT_FIRE = 1
ELEMENT_WATER = 2
ELEMENT_AIR = 3
ELEMENT_EARTH = 4

---@alias DemonRageBonusType
---|`DEMON_RAGE_BONUS_HEALTH`
---|`DEMON_RAGE_BONUS_DISABLE_ABILITY`
---|`DEMON_RAGE_BONUS_DEFENCE`
---|`DEMON_RAGE_BONUS_ATTACK`
---|`DEMON_RAGE_BONUS_INITIATIVE`
---|`DEMON_RAGE_BONUS_ACCURACY`
---|`DEMON_RAGE_BONUS_DAMAGE`
---|`DEMON_RAGE_BONUS_SPEED`
---|`DEMON_RAGE_BONUS_SPELLPOWER_MULT`
DEMON_RAGE_BONUS_HEALTH = 1
DEMON_RAGE_BONUS_DISABLE_ABILITY = 2
DEMON_RAGE_BONUS_DEFENCE = 3
DEMON_RAGE_BONUS_ATTACK = 4
DEMON_RAGE_BONUS_INITIATIVE = 5
DEMON_RAGE_BONUS_ACCURACY = 6
DEMON_RAGE_BONUS_DAMAGE = 7
DEMON_RAGE_BONUS_SPEED = 8
DEMON_RAGE_BONUS_SPELLPOWER_MULT = 9

TIER_TABLES = {}

TOWN_DWELLS =
{
	[TOWN_HEAVEN]     = {1, 3, 5, 7, 9, 11, 13},
	[TOWN_INFERNO]    = {15, 17, 19, 21, 23, 25, 27},
	[TOWN_NECROMANCY] = {29, 31, 33, 35, 37, 39, 41},
	[TOWN_PRESERVE]   = {43, 45, 47, 49, 51, 53, 55},
	[TOWN_ACADEMY]    = {57, 59, 61, 63, 65, 67, 69},
	[TOWN_DUNGEON]    = {71, 73, 75, 77, 79, 81, 83},
	[TOWN_FORTRESS]   = {92, 94, 96, 98, 100, 102, 104},
	[TOWN_STRONGHOLD]    = {117, 119, 121, 123, 125, 127, 129}
}
