--- skills --- 

-- common
doFile("/scripts/Common/Skills/Catapult/script.lua")
doFile("/scripts/Common/Skills/DemonicRetaliation/script.lua")
doFile("/scripts/Common/Skills/GrailVision/script.lua")
doFile("/scripts/Common/Skills/Readiness/script.lua")
doFile("/scripts/Common/Skills/SealOfProtection/script.lua")
doFile("/scripts/Common/Skills/ShakeGround/script.lua")
doFile("/scripts/Common/Skills/SorceryDefence/script.lua")
doFile("/scripts/Common/Skills/TripleCatapult/script.lua")

-- duel only
doFile("/scripts/Duel/Skills/Catapult/script.lua")
doFile("/scripts/Duel/Skills/DarkRitual/script.lua")
doFile("/scripts/Duel/Skills/DeathThread/script.lua")
doFile("/scripts/Duel/Skills/Diplomacy/script.lua")
doFile("/scripts/Duel/Skills/DisguiseAndReckon/script.lua")
doFile("/scripts/Duel/Skills/Estates/script.lua")
doFile("/scripts/Duel/Skills/ExpertTrainer/script.lua")
doFile("/scripts/Duel/Skills/FineRune/script.lua")
doFile("/scripts/Duel/Skills/ForestLeader/script.lua")
doFile("/scripts/Duel/Skills/FortunateAdventurer/script.lua")
doFile("/scripts/Duel/Skills/GoblinSupport/script.lua")
doFile("/scripts/Duel/Skills/HauntedMines/script.lua")
doFile("/scripts/Duel/Skills/HeraldOfDeath/script.lua")
doFile("/scripts/Duel/Skills/RoadHome/script.lua")
doFile("/scripts/Duel/Skills/Logistics/script.lua")
doFile("/scripts/Duel/Skills/LordOfUndead/script.lua")
doFile("/scripts/Duel/Skills/Mentorship/script.lua")
doFile("/scripts/Duel/Skills/Mysticism/script.lua")
doFile("/scripts/Duel/Skills/Navigation/script.lua")