ARTIFACT_BLUEPRINT_DWELL_13 = 117
ARTIFACT_BLUEPRINT_DWELL_47 = 118
ARTIFACT_BLUEPRINT_SPECIAL = 119
ARTIFACT_BLUEPRINT_MGUILD = 120

blueprints_rmg = {
    presented_buildings_by_race = {
        [TOWN_HEAVEN] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_2,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_5, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_ACADEMY] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_2, TOWN_BUILDING_SPECIAL_3,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_DUNGEON] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_3,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_5, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_FORTRESS] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_2, TOWN_BUILDING_SPECIAL_3,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_5, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_INFERNO] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_2, TOWN_BUILDING_SPECIAL_3,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_5, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_NECROMANCY] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_2, TOWN_BUILDING_SPECIAL_3,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_PRESERVE] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH, TOWN_BUILDING_MAGIC_GUILD,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_0, TOWN_BUILDING_SPECIAL_2, TOWN_BUILDING_SPECIAL_4, 
            TOWN_BUILDING_SPECIAL_5, TOWN_BUILDING_SPECIAL_6
        },
        [TOWN_STRONGHOLD] = {
            TOWN_BUILDING_TOWN_HALL, TOWN_BUILDING_FORT, 
            TOWN_BUILDING_TAVERN, TOWN_BUILDING_MARKETPLACE, 
            TOWN_BUILDING_BLACKSMITH,
            TOWN_BUILDING_DWELLING_1, TOWN_BUILDING_DWELLING_2, 
            TOWN_BUILDING_DWELLING_3, TOWN_BUILDING_DWELLING_4, TOWN_BUILDING_DWELLING_5,
            TOWN_BUILDING_DWELLING_6, TOWN_BUILDING_DWELLING_7, 
            TOWN_BUILDING_GRAIL, TOWN_BUILDING_SHIPYARD,
            TOWN_BUILDING_SPECIAL_1, TOWN_BUILDING_SPECIAL_2, TOWN_BUILDING_SPECIAL_3,
            TOWN_BUILDING_SPECIAL_4, TOWN_BUILDING_SPECIAL_5, TOWN_BUILDING_SPECIAL_6
        }
    }
}

function Blueprints_GetTownLevel(town)
    local level = 0
    for i, building in blueprints_rmg.presented_buildings_by_race[GetTownRace(town)] do
        level = level + GetTownBuildingLevel(town, building)
    end
    return level
end